### ISSUE TITLE
ida

### ISSUE THREAD

**Issue by morhaimi** [lin2j/easy-deploy#5]
![35c90e6c5d15eef19f9bc639ac9f5f4](https://github.com/lin2j/easy-deploy/assets/79240179/7a5bd932-9637-4b86-befe-74b1a7d66884)
![de1e0bb68f44b17f82a409419a28975](https://github.com/lin2j/easy-deploy/assets/79240179/0fe00cd3-197b-437c-b215-c34c18d3019f)
在idea2023.3.5版本中使用插件，测试连接没问题，但是点terminal后就进入一个unnamed小窗口了

**Comment by lin2j** [comment]
插件在点击开启服务器的终端之后，会调用一个终端组件，但是这个组件在 2023.3.5 中废除了，所以会出现异常。在 1.2.10 版本之后，我临时将插件的适用版本改为 193.5662—232.*，来规避这个问题。目前我正在研究如何适配 233.* 的版本。

**Comment by lin2j** [comment]
问题已经在 1.3.2 版本修复，请使用最新版本的插件。 [V1.3.2](https://github.com/lin2j/easy-deploy/releases/download/v1.3.2/Easy-Deploy-1.3.2.zip)
