### ISSUE TITLE
【建议】并行部署

### ISSUE THREAD

**Issue by klaus-cicd** [lin2j/easy-deploy#8]
痛点：同时部署至多个服务器时，上传任务目前是依次执行，耗费时间
<img width="930" alt="image" src="https://github.com/user-attachments/assets/1e4e85d0-6e52-42b6-a46d-c121d7717e93">
优化建议：多个服务同时上传并执行脚本

**Comment by dhshu** [comment]
真的需要这个

**Comment by lin2j** [comment]
好的，下个版本加上去。目前功能都是根据自己的工作流设计的，有需要优化的功能会尽量尽快地处理 🤔

**Comment by lin2j** [comment]
1.3.7 已增加
